### ISSUE TITLE
Block Rendering Issue

### ISSUE THREAD

**Issue by trankin** [kirbysayshi/vash#43]
I'm running a simple test using node, reading the contents of a .vash file which references a layout which includes one block.  I then compile and execute the file read in, and everything seems to run without any runtime errors, however the output for the block only displays [VASHMARK-7668312:block-content]

I'm sure I'm missing something simple, but I thought a quick review from the expert might shortcut some digging.

I've posted the example here: https://bitbucket.org/trankin/vash-testing.git

**Comment by fghhfg** [comment]
@trankin you code don't work... :-1: 

```js
var vash = require('vash');
var fs = require('fs');

var pageText = fs.readFileSync('index.vash').toString();
var page = vash.compile(pageText);
console.log(page());
```

```js
λ nnode main.js
C:\Users\user\a3\node_modules\vash\runtime.js:268
  throw e;
        ^
Error: Problem while rendering template at line 0, character 0.                                           
Original message: ENOENT: no such file or directory, open 'C:\Users\user\a3\_layout'.                     
Context:                                                                                                  
                                                                                                          
     1 | @html.extend('_layout', function(model){                                                         
     2 |                                                                                                  
     3 |     @html.append('layout_content', function(model) {                                             
     4 |         <h1>Home -> Index @model.title</h1>                                                      
     5 |     })                                                                                           
     6 |                                                                                                  
     7 |     @html.append('layout_footer', function(model){                                               
     8 |         <ul>                                                                                     
     9 |             <li>Terms</li>                                                                       
    10 |             <li>Privacy</li>                                                                     
    11 |         </ul>                                                                                    
    12 |     })                                                                                           
                                                                                                          
                                                                                                          
    at Error (native)                                                                                     
    at Object.fs.openSync (fs.js:549:18)                                                                  
    at Object.fs.readFileSync (fs.js:397:15)                                                              
    at Object.vash.loadFile (C:\Users\user\a3\node_modules\vash\lib\helpers\layout.js:66:26)              
    at Helpers.helpers.extend (C:\Users\user\a3\node_modules\vash\lib\helpers\layout.js:188:8)            
    at eval (eval at <anonymous> (C:\Users\user\a3\node_modules\vash\runtime.js:308:26), <anonymous>:8:33)
    at linked (C:\Users\user\a3\node_modules\vash\runtime.js:348:14)                                      
    at Object.<anonymous> (C:\Users\user\a3\main.js:6:13)                                                 
    at Module._compile (module.js:430:26)                                                                 
    at Object.Module._extensions..js (module.js:448:10)                                                   
```
