### ISSUE TITLE
Layout helpers cannot handle empty files (and misreport errors)

### ISSUE THREAD

**Issue by stimpy77** [kirbysayshi/vash#46]
Being as I'm new to vash (and for that matter nodejs development) I might have overlooked something, but while the vash-express-sample demonstrates using @html.include() without issue in a view, it doesn't work when @html.include() is used in the layout file. I ran into this problem first in my own app and sought to validate that the issue is reproducible in the sample. It is. Perhaps this is by design, or perhaps there is a workaround?
The referenced partial is a sometimes-used feature that other layout files might reuse.

    500 TypeError: object is not a function
        at C:\Users\jdavis\vash\vash-express-example\node_modules\vash\build\vash.js:575:13
        at Object.vash.loadFile (C:\Users\jdavis\vash\vash-express-example\node_modules\vash\build\vash.js:565:10)
        at View.vash.renderFile [as engine] (C:\Users\jdavis\vash\vash-express-example\node_modules\vash\build\vash.js:571:8)
        at View.render (C:\Users\jdavis\vash\vash-express-example\node_modules\express\lib\view.js:75:8)
        at Function.app.render (C:\Users\jdavis\vash\vash-express-example\node_modules\express\lib\application.js:505:10)
        at ServerResponse.res.render (C:\Users\jdavis\vash\vash-express-example\node_modules\express\lib\response.js:718:7)
        at exports.index (C:\Users\jdavis\vash\vash-express-example\routes\index.js:7:7)
        at callbacks (C:\Users\jdavis\vash\vash-express-example\node_modules\express\lib\router\index.js:162:37)
        at param (C:\Users\jdavis\vash\vash-express-example\node_modules\express\lib\router\index.js:136:11)
        at pass (C:\Users\jdavis\vash\vash-express-example\node_modules\express\lib\router\index.js:143:5)

**Comment by kirbysayshi** [comment]
This should be implemented as of >= 0.8.0!
