### ISSUE TITLE
Node.js - express: where is the error? Make error more informative

### ISSUE THREAD

**Issue by unlight** [kirbysayshi/vash#49]
```js
var vash = require("vash");
vash.config.debugParser = true;
vash.config.debugCompiler = true;
vash.config.useWith = true;
```
Browser output:
```
TypeError: object is not a function
   at ~\node_modules\vash\build\vash.js:2213:4
   at Object.vash.loadFile (~\node_modules\vash\build\vash.js:2072:10)
   at helpers.extend (~\node_modules\vash\build\vash.js:2190:8)
   at eval (eval at <anonymous> (~\node_modules\vash\build\vash.js:1820:24), <anonymous>:9:21)
   at linked (~\node_modules\vash\build\vash.js:1860:12)
   at ~\node_modules\vash\build\vash.js:2082:21
   at Object.vash.loadFile (~\node_modules\vash\build\vash.js:2070:10)
   at View.vash.renderFile [as engine] (~\node_modules\vash\build\vash.js:2078:8)
   at View.render (~\node_modules\express\lib\view.js:93:8)
   at EventEmitter.app.render (~\node_modules\express\lib\application.js:530:10) 
```
I do not see where is the error occurred. Neither in browser or in console.

What object?
Where is it?
What line?

Node v.11.13, vash 0.7.12-1

**Comment by kirbysayshi** [comment]
@unlight if you have more info, please reopen this issue. In the meantime, I think this ended up mostly being the same issue as #46, which will be fixed in vash 0.8.0. If you want to try that version, you can do `npm install vash@beta`.
