### ISSUE TITLE
Write after end error - how can I find the line number this error occrred?

### ISSUE THREAD

**Issue by steebchen** [kirbysayshi/vash#74]
Sometimes, I get the following error:

    Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at ServerResponse.res.write (/home/myapp/node_modules/express/node_modules/connect/lib/middleware/compress.js:110:17)
    at ServerResponse.res.end (/home/myapp/node_modules/express/node_modules/connect/lib/middleware/compress.js:116:14)
    at ServerResponse.res.send (/home/myapp/node_modules/express/lib/response.js:153:8)
    at fn (/home/myapp/node_modules/express/lib/response.js:797:10)
    at /home/myapp/node_modules/vash/build/vash.js:2082:4
    at Object.vash.loadFile (/home/myapp/node_modules/vash/build/vash.js:2070:10)
    at View.vash.renderFile [as engine] (/home/myapp/node_modules/vash/build/vash.js:2078:8)
    at View.render (/home/myapp/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/home/myapp/node_modules/express/lib/application.js:504:10)

How can I find the actual file and line number where this occurred? I have a very large app and I would never find this error when searching manually.

**Comment by steebchen** [comment]
Found it out by increasing the error stack size to 20:
`Error.stackTraceLimit = 20;`

**Comment by kirbysayshi** [comment]
sorry for not responding sooner. If you update to a newer vash version, you should get better error reporting as well, especially when using the server-side layout helpers.

**Comment by steebchen** [comment]
Yeah, I tried upgrading some weeks/months ago, but then all pages gave an error with 'object is not a function' (always on line 1 col 1) but I can try it again with the latest version, if it should not work I'll comment here again.

**Comment by kirbysayshi** [comment]
Please do! Or open a separate bug, since this is a separate issue related to the upgrade :)
